data/users/jaynarayan-vaishnav.json
=> Add Volunteer Jaynarayan Vaishnav.

data/users/jaynarayan-vaishnav.json
Full name causing alignment issues.
=> refactor: Jaynarayan Vaishnav -> Jay vaishnav

data/users/AaryaChopkar.json, data/users/accodes21.json
Added new Volunteer.
Code matches existing pattern.
=> Add new Volunteer AaryaChopkar

data/users/Varun-Bhabhra.json
Add new volunteer Varun Bhabhra.
=> Add new volunteer Varun Bhabhra

data/users/HeriYantodotDev.json
Hi! I've just added a new user
=> Add new volunteer Heri Yanto

data/users/AmitMaity.json
Add new volunteer Amit Maity
```Android Developer```
=> chore: add volunteer maityamit

data/users/bruxx-6243.json
Hey @codewithvoid I've made the changes you specified me.
=> chore: add volunteer bruxx-6243

data/users/miraz-mondal.json
I want to be a part of AskDevs as a volunteer as I love to help other person!
=> chore: add volunteer miraz-mondal

data/users/TuhinBar.json
Got some issues with the previous PR. So made a new one.
=> chore: add volunteer TuhinBar

data/users/Aayushd18.json
Adding myself as the volunteer.
Cheers!!
=> chore: add volunteer Aayushd18

data/users/VaibhavSinghDev.json
Added the volunteer details to the JSON file.
=> chore: add volunteer VaibhavSinghDev

data/users/tobySolutions.json
=> chore: add volunteer tobySolutions

data/users/krshkun.json
=> chore: add krshkun

data/users/rupali-codes.json
Added rupali-codes in volunteer as web developer
=> chore: add volunteer rupali-codes

data/users/zelfroster.json
Add me Sensei!!
Glad to help. 😄
=> chore: add volunteer zelfroster

package-lock.json, src/pages/index.js
=> fix: fixes mini issues #114

data/users/JamesSimel.json
Please review I have already corrected all the errors!
=> chore: add volunteer JamesSimel

data/users/bitethecode.json
=> chore: add volunteer bitethecode

data/users/aksh-kr.json
=> chore: update volunteer details aksh-kr

data/users/sumanpaikdev.json
Followed instructions via Readme.md file.
=> chore: add volunteer sumanpaikdev

data/users/KrishnaTheCoder756.json
chore: add volunteer KrishnaTheCoder756
=> chore: add volunteer KrishnaTheCoder756

data/users/vasujhawar2001.json
None.
Let me know if any changes, and love this project.
=> chore: add volunteer vasujhawar2001

data/users/KrishnaTheCoder756.json
=> fix: fixes #225

data/users/vedantnn7.json
=> fix: fixes #229

data/users/Gagan1708.json
chore: add volunteer Gagan1708
=> chore: add volunteer Gagan1708

data/users/chozeur.json
Hi all, glad to take part in this project !
=> chore: add volunteer chozeur

data/users/rahulpandey70.json
=> chore: add volunteer rahulpandey70

data/users/ShaikMoAbdullah.json
chore: add ShaikMoAbdullah profile to AskDevs
=> chore: add volunteer ShaikMoAbdullah

data/users/eskayML.json
=> chore: add volunteer eskayML 

data/users/maniadhikari.json
=> fix: fixes #261

src/pages/index.js
Now, on the toggle of the button, we can deselect category, #260
=> feat: de-select category

data/users/hartpoli.json
=> chore: add volunteer hartpoli

data/users/Palakkgoyal.json
I want to volunteer with you and help other developers and expand my knowledge
=> chore: add volunteer Palakkgoyal

data/users/dev-divyansh.json
=> chore: add volunteer dev-divyansh

data/users/JohnSaidi.json
Adding _JohnSd as a New tech twitter volunteers.
=> chore: add volunteer JohnSaidi
